---
controller:
  config:
    compute-full-forward-for: "true"
    use-forwarded-headers: "true"
    proxy-body-size: "0"
  ingressClass: external-nginx
  ingressClassResource:
    enabled: true
    default: false
  replicaCount: 1
  service:
    annotations:
       service.beta.kubernetes.io/aws-load-balancer-type: "nlb"